function ViewOptions() {
  return (
    <div>
      <div>
        <h2>Temperature</h2>
        <div>Icon</div>
        <h3>Stat</h3>
      </div>
      <div>
        <h2>Precipitation</h2>
        <div>Icon</div>
        <h3>Stat</h3>
      </div>
      <div>
        <h2>Humidity</h2>
        <div>Icon</div>
        <h3>Stat</h3>
      </div>
      <div>
        <h2>UV Index</h2>
        <div>Icon</div>
        <h3>Stat</h3>
      </div>
      <div>
        <h2>Visibility</h2>
        <div>Icon</div>
        <h3>Stat</h3>
      </div>
      <div>
        <h2>Clouds</h2>
        <div>Icon</div>
        <h3>Stat</h3>
      </div>
      <div>
        <h2>Wind</h2>
        <div>Icon</div>
        <h3>Stat</h3>
      </div>
      <div>
        <h2>Sun</h2>
        <div>Icon</div>
        <h3>Stat</h3>
      </div>
      <div>
        <h2>Moon</h2>
        <div>Icon</div>
        <h3>Stat</h3>
      </div>
      <div>
        <h2>Snow</h2>
        <div>Icon</div>
        <h3>Stat</h3>
      </div>
      <div>
        <h2>Waves</h2>
        <div>Icon</div>
        <h3>Stat</h3>
      </div>
    </div>
  )
}

export default ViewOptions;